import { Bed, Hotel, Waves, Package, Users, Compass, Eye } from 'lucide-react'

// Mock data for ABS_Landing stories
export const roomOptions = [
  {
    id: 'deluxe',
    title: "Live luxury’s pinnacle by the sea",
    roomType: 'DELUXE GOLD',
    description: 'True rock stars look down from above. A space covering 33 square metres with spectacular sea views, a private furnished terrace and elegant décor for a superior experience from the fifth floor upwards. Exceed even your own expectations, and relax with chromotherapy lighting that you can personalise. Lie back like a rock star in a luxurious king-sized bed, or in two full-sized single beds, and enjoy this room\'s ultra-modern facilities: thoughtfully selected state-of-the-art furniture, a 43 SMART TV screen, a dock station and a comfortable reading corner with a sofa bed.',
    price: 302,
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/c37cc822-a6bf-4345-93f8-deb22d186d10/image.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/49a54c09-0945-4a87-893d-8d28d79e0f5b/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/9d29265c-3fc9-4c70-b953-7e3335f200aa/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/61c2250a-8967-446e-91b4-2bc50bf9be1a/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '30 to 35 m2 / 325 to 375 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Desk',
      'Hairdryer',
      'In Main Building',
      'Iron & Board',
      'Landmark View',
      'Magnifying mirror',
      'Minibar',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Shoe kit',
      'Smart TV',
      'Table and chairs set',
      'Tea Set'
    ],
  },
  {
    id: 'deluxe-swim-up',
    title: "Dive in from your private terrace",
    roomType: 'DELUXE SWIM-UP',
    description: 'What about adding to your Double room a furnished outdoors terrace with a direct access to the meandering pool and private sun lounger waiting for you to enjoy the splash.',
    price: 468,
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt634/cdf69769-f553-4c82-aa06-e3e8867954fb/image.webp',
    images: [
        'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt634/cdf69769-f553-4c82-aa06-e3e8867954fb/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt634/c46d320b-89d6-4975-9af0-febbeaf4b450/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '30 to 35 m2 / 325 to 375 sqft',
      'AC',
      'Afternoon Sun',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Desk',
      'Hairdryer',
      'Iron & Board',
      'Magnifying mirror',
      'Minibar',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Piazza View',
      'Pillow Menu',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Shared Pool',
      'Shoe kit',
      'Smart TV',
      'Table and chairs set',
      'Tea Set',
      'Terrace'
    ],
  },
  {
    id: 'rocksuite',
    roomType: 'ROCK SUITE',
    title: "Supreme luxury with divine views",
    description: 'Our contemporary Hard Rock Ibiza Suites perfectly capture the authenticity and irreverence of rock \'n\' roll with the sensuality and sophistication of Ibiza Island. Three connecting spaces - Living/ lounge, bedroom and bathroom - allowing you to decide when it\'s time for plugging in or chilling out. Totally unpredictable, totally Ibiza Hard Rock.',
    price: 378,
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/3e7e2260-63e3-4934-9358-ebf08bb6d96a/image.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/3e7e2260-63e3-4934-9358-ebf08bb6d96a/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/cb767423-cda2-4345-9008-dd1a42573ead/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/04386083-34f1-4175-8379-685ae5071a12/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '60 to 70 m2 / 645 to 755 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Coffee Machine',
      'Desk',
      'Hairdryer',
      'Hydromassage Bathtub',
      'Iron & Board',
      'Landmark View',
      'Lateral Streets View',
      'Living Room',
      'Magnifying mirror',
      'Minibar',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Pool View',
      'Premium Wi-Fi',
      'Rain shower',
      'Recyclables Coffee Capsules',
      'Safe',
      'Shoe kit',
      'Smart TV',
      'Sofa Bed - Double',
      'Table and chairs set',
      'Tea Set'
    ],
  },
  {
    id: '80s-suite',
    roomType: '80S SUITE',
    title: "80s nostalgia unleashed",
    description: '60 square-meter space with an 80s setting, among which vinyl, mirror ball, music cassettes with 80s music and some 80\'s gifts like a welcome kit that includes a t-shirt.',
    price: 606,
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt635/24fa2b9d-307c-4d23-9021-eb174520dbc0/image.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt641/850e6840-cc2b-48f8-9059-3a64d2b9b097/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt641/f356e89d-6dca-443e-9ac4-9bb975a84b07/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt641/e69fa285-5242-4992-831b-7e67d401ba00/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '60 to 70 m2 / 645 to 755 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Coffee Machine',
      'Desk',
      'Hairdryer',
      'Hydromassage Bathtub',
      'Iron & Board',
      'King Size Bed',
      'Landmark View',
      'Living Room',
      'Magnifying mirror',
      'Minibar',
      'Morning Sun',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Pool View',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Smart TV',
      'Sofa Bed - Double',
      'Shoe kit',
      'Table and chairs set',
      'Tea Set'
    ],
  },
  {
    id: 'rock-suite-diamond',
    roomType: 'ROCK SUITE DIAMOND',
    title: "Glam rock with infinite views",
    description: 'Llega a la cima del rock en este espacio de 75 metros cuadrados auténticamente inspirado en estrellas del rock y que ofrece ese toque de vida glamourosa. Con una exuberancia sin límites, incluye unas vistas infinitas que se prolongan desde la suite hasta la terraza, y una bañera de grifería vista en mitad del dormitorio principal para que no te pierdas el mínimo detalle del paisaje mientras disfrutas de un placer infinito. Estancia de 75 metros cuadrados con capacidad hasta cuatro personas.',
    price: 493,
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt643/5a6459fb-7a86-4d9d-9d9d-acd9a80033d5/original.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt643/5a6459fb-7a86-4d9d-9d9d-acd9a80033d5/original.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt643/e58aeb29-1399-422a-906f-6efc480221c4/original.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt643/40f0715d-3d66-49b7-b71b-cbd8e9d6ed1c/original.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '60 to 70 m2 / 645 to 755 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Coffee Machine',
      'Desk',
      'Hairdryer',
      'Hydromassage Bathtub',
      'Iron & Board',
      'King Size Bed',
      'Landmark View',
      'Living Room',
      'Magnifying mirror',
      'Minibar',
      'Morning Sun',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Pool View',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Smart TV',
      'Sofa Bed - Double',
      'Shoe kit',
      'Table and chairs set',
      'Tea Set'
    ],
  },
  {
    id: 'rock-suite-legend',
    roomType: 'ROCK SUITE LEGEND',
    title: "Live the rock legend",
    description: 'Llega a la cima del rock en este espacio de 75 metros cuadrados auténticamente inspirado en estrellas del rock y que ofrece ese toque de vida glamourosa. Con una exuberancia sin límites, incluye unas vistas infinitas que se prolongan desde la suite hasta la terraza, y una bañera de grifería vista en mitad del dormitorio principal para que no te pierdas el mínimo detalle del paisaje mientras disfrutas de un placer infinito. Estancia de 75 metros cuadrados con capacidad hasta cuatro personas.',
    price: 867,
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt644/b15ce84f-709d-4d46-a0af-2654a645c643/original.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt644/b15ce84f-709d-4d46-a0af-2654a645c643/original.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt644/6f7ea7a0-68df-47ec-8902-0e9a93eb41c1/original.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt644/7dc6a198-3225-49c0-b89e-5fcc4abcf4dc/original.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '60 to 70 m2 / 645 to 755 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Coffee Machine',
      'Desk',
      'Hairdryer',
      'Hydromassage Bathtub',
      'Iron & Board',
      'King Size Bed',
      'Landmark View',
      'Living Room',
      'Magnifying mirror',
      'Minibar',
      'Morning Sun',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Pool View',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Smart TV',
      'Sofa Bed - Double',
      'Shoe kit',
      'Table and chairs set',
      'Tea Set'
    ],
  },
]

export const bedsOptions = [
  {
    id: 'twin',
    name: '2 x Twin Beds',
    description: 'Two separate single beds',
    price: 0,
    icon: 'bed-twin',
    label: '2 x Twin Beds',
  },
  {
    id: 'king',
    name: 'King Size Bed',
    description: 'One extra-large king-sized bed',
    price: 5,
    icon: 'bed-king',
    label: 'King Size Bed',
  },
  {
    id: 'sofa',
    name: 'Sofa Bed - Single',
    description: 'Single sofa bed for additional sleeping space',
    price: 2,
    icon: 'sofa',
    label: 'Sofa Bed - Single',
  },
]

// export const roomSizeOptions = [
//   {
//     id: 'large-size',
//     name: '35 to 40 m2 / 375 to 430 sqft',
//     description: 'Spacious room with ample living space',
//     price: 4,
//     icon: 'home',
//     label: '35 to 40 m2 / 375 to 430 sqft',
//   },
// ]

export const featuresOptions = [
  {
    id: 'adapted-room',
    name: 'Adapted Room',
    description: 'Accessible room designed for guests with disabilities',
    price: 0,
    icon: 'accessibility',
    label: 'Adapted Room',
  },
]

export const orientationOptions = [
  {
    id: 'afternoon-sun',
    name: 'Afternoon Sun',
    description: 'West-facing room with warm afternoon sunlight',
    price: 2,
    icon: 'sun',
    label: 'Afternoon Sun',
  },
  {
    id: 'all-day-sun',
    name: 'All-day Sun',
    description: 'South-facing room with sunlight throughout the day',
    price: 6,
    icon: 'sun',
    label: 'All-day Sun',
  },
]

// export const bestChoiceOptions = [
//   {
//     id: 'best-views',
//     name: 'Best views',
//     description: 'Rooms with the most spectacular views available',
//     price: 6,
//     icon: 'eye',
//     label: 'Best views',
//   },
// ]

export const locationOptions = [
  {
    id: 'main-building',
    name: 'In Main Building',
    description: 'Located in the main hotel building',
    price: 0,
    icon: 'building',
    label: 'In Main Building',
  },
  {
    id: 'main-restaurant',
    name: 'Close to Main Restaurant',
    description: 'Convenient access to the main restaurant',
    price: 2,
    icon: 'utensils',
    label: 'Close to Main Restaurant',
  },
  {
    id: 'miniclub',
    name: 'Close to Miniclub',
    description: 'Perfect for families with children',
    price: 2,
    icon: 'baby',
    label: 'Close to Miniclub',
  },
  {
    id: 'pool',
    name: 'Close to Pool',
    description: 'Easy access to swimming facilities',
    price: 4,
    icon: 'waves',
    label: 'Close to Pool',
  },
  {
    id: 'wellness',
    name: 'Close to Wellness',
    description: 'Near spa and wellness facilities',
    price: 2,
    icon: 'heart',
    label: 'Close to Wellness',
  },
  {
    id: 'beach-access',
    name: 'Direct Access to Beach',
    description: 'Direct pathway to the beach',
    price: 6,
    icon: 'umbrella',
    label: 'Direct Access to Beach',
  },
  {
    id: 'quiet-zone',
    name: 'Quiet Hotel Zone',
    description: 'Peaceful area for relaxation',
    price: 4,
    icon: 'volume-x',
    label: 'Quiet Hotel Zone',
  },
]

export const floorOptions = [
  {
    id: 'ground-floor',
    name: 'Ground Floor Location',
    description: 'Easy access without elevators',
    price: 6,
    icon: 'home',
    label: 'Ground Floor Location',
  },
  {
    id: 'upper-floor',
    name: 'Upper Floor',
    description: 'Higher floors with better views',
    price: 6,
    icon: 'arrow-up',
    label: 'Upper Floor',
  },
]

export const distributionOptions = [
  {
    id: 'garden-access',
    name: 'Access to Garden',
    description: 'Direct access to hotel gardens',
    price: 4,
    icon: 'flower',
    label: 'Access to Garden',
  },
  {
    id: 'pool-access',
    name: 'Access to Pool',
    description: 'Direct access to swimming pool',
    price: 10,
    icon: 'waves',
    label: 'Access to Pool',
  },
  {
    id: 'balcony',
    name: 'Balcony',
    description: 'Private balcony with outdoor seating',
    price: 2,
    icon: 'door-open',
    label: 'Balcony',
  },
  {
    id: 'connecting-room',
    name: 'Connecting Room',
    description: 'Adjacent rooms with connecting door',
    price: 15,
    icon: 'link',
    label: 'Connecting Room',
  },
  {
    id: 'living-room',
    name: 'Living Room',
    description: 'Separate living area in the room',
    price: 10,
    icon: 'sofa',
    label: 'Living Room',
  },
  {
    id: 'terrace',
    name: 'Terrace',
    description: 'Large outdoor terrace area',
    price: 6,
    icon: 'sun',
    label: 'Terrace',
  },
]

export const viewOptions = [
  {
    id: 'city-view',
    name: 'City View',
    description: 'Room with a view of the city',
    price: 0,
    icon: 'city-view',
    label: 'City View',
  },
  {
    id: 'garden-view',
    name: 'Garden View',
    description: 'Room with a view of the garden',
    price: 2,
    icon: 'corner-up-right',
    label: 'Garden View',
  },
  {
    id: 'lateral-sea-view',
    name: 'Lateral Sea View',
    description: 'Room with a lateral view of the sea',
    price: 6,
    icon: 'waves',
    label: 'Lateral Sea View',
  },
  {
    id: 'pool-view',
    name: 'Pool View',
    description: 'Room with a view of the pool',
    price: 5,
    icon: 'waves',
    label: 'Pool View',
  },
  {
    id: 'sea-frontal-view',
    name: 'Sea Frontal View',
    description: 'Room with a frontal view of the sea',
    price: 10,
    icon: 'waves',
    label: 'Sea Frontal View',
  },
  {
    id: 'stage-view',
    name: 'Stage View',
    description: 'Room with a view of the stage',
    price: 6,
    icon: 'corner-up-right',
    label: 'Stage View',
  },
]

export const exactViewOptions = [
  {
    id: 'city-view',
    name: 'Exact view.',
    description: 'Room with a view of the city',
    price: 0,
    icon: 'arrow-up',
    imageUrl:
      'https://hvdatauatstgweu.blob.core.windows.net/roommediaimages/h83/r18127/outside/5630a049-2134-485a-846c-9b01d0728c31/image_c.webp',
  },
  {
    id: 'garden-view',
    name: 'Exact view.',
    description: 'Room with a view of the garden',
    price: 2,
    icon: 'corner-up-right',
    imageUrl:
      'https://hvdatauatstgweu.blob.core.windows.net/roommediaimages/h83/r18174/outside/2b47e562-59f0-41da-9617-16ea6c310639/image_c.webp',
  },
  {
    id: 'lateral-sea-view',
    name: 'Exact view.',
    description: 'Room with a lateral view of the sea',
    price: 6,
    icon: 'waves',
    imageUrl:
      'https://hvdatauatstgweu.blob.core.windows.net/roommediaimages/h83/r18231/outside/dd68f329-aab9-4b80-a4f7-4046e0ace158/image_c.webp',
  },
  {
    id: 'pool-view',
    name: 'Exact view.',
    description: 'Room with a view of the pool',
    price: 5,
    icon: 'waves',
    imageUrl:
      'https://hvdatauatstgweu.blob.core.windows.net/roommediaimages/h83/r18260/outside/5f07a642-07b0-44aa-aa67-f6141c3aec04/image_c.webp',
  },
  {
    id: 'sea-frontal-view',
    name: 'Exact view.',
    description: 'Room with a frontal view of the sea',
    price: 10,
    icon: 'waves',
    imageUrl:
      'https://hvdatauatstgweu.blob.core.windows.net/roommediaimages/h83/r18321/outside/04424aec-0f76-4c0c-98a7-ef0e3d550483/image_c.webp',
  },
  {
    id: 'stage-view',
    name: 'Exact view.',
    description: 'Room with a view of the stage',
    price: 6,
    icon: 'corner-up-right',
    imageUrl:
      'https://hvdatauatstgweu.blob.core.windows.net/roommediaimages/h83/r18364/outside/bd15466f-eef8-4464-bc45-d5dc5a6daeba/image_c.webp',
  },
  {
    id: 'stage-view-2',
    name: 'Exact view.',
    description: 'Room with a view of the stage',
    price: 6,
    icon: 'corner-up-right',
    imageUrl:
      'https://cdn.hotelverse.tech/roommediaimages/h83/r18017/outside/894ba4dc-1796-441d-afe8-af844e31fae5/image_c.webp',
  },
  {
    id: 'sea-view-2',
    name: 'Exact view.',
    description: 'Room with a view of the stage',
    price: 15,
    icon: 'corner-up-right',
    imageUrl:
      'https://cdn.hotelverse.tech/roommediaimages/h83/r18024/outside/4f2bf927-81de-406e-966f-f233af5e561f/image_c.webp',
  },
  {
    id: 'sea-view-3',
    name: 'Exact view.',
    description: 'Room with a view of the stage',
    price: 5,
    icon: 'corner-up-right',
    imageUrl:
      'https://cdn.hotelverse.tech/roommediaimages/h83/r18028/outside/80b088b2-b4aa-4e81-973f-4261b7a9c9ed/image_c.webp',
  },
  {
    id: 'sea-view-4',
    name: 'Exact view.',
    description: 'Room with a view of the stage',
    price: 5,
    icon: 'corner-up-right',
    imageUrl:
      'https://cdn.hotelverse.tech/roommediaimages/h83/r18039/outside/7fe3b203-7a33-4398-a127-446217b00e55/image_c.webp',
  },
  {
    id: 'sea-view-5',
    name: 'Exact view.',
    description: 'Room with a view of the stage',
    price: 12,
    icon: 'corner-up-right',
    imageUrl:
      'https://cdn.hotelverse.tech/roommediaimages/h83/r18054/outside/9eb8a6f8-33e2-4cba-b020-4d95f1171f5c/image_c.webp',
  },
  {
    id: 'sea-view-6',
    name: 'Exact view.',
    description: 'Room with a view of the stage',
    price: 12,
    icon: 'corner-up-right',
    imageUrl:
      'https://cdn.hotelverse.tech/roommediaimages/h83/r18054/outside/9eb8a6f8-33e2-4cba-b020-4d95f1171f5c/image_c.webp',
  },
]

export const roomSelectionMap = {
  id: 'room-selection',
  title: 'Choose your Superior Room!',
  description: 'Choose from our selection of premium rooms and suites',
  url: 'https://map-uat.hotelverse.tech/Webmap/en/ChooseYourRoom?config=eyJjbGllbnRJZCI6MSwiaG90ZWxJZCI6ODMsImN1cnJlbmN5IjoiRVVSIiwiYWNjZXNzVG9rZW5IViI6ImV5SnphV2R1WVhSMWNtVWlPaUk0TWpSbU5EUmtaakZqWXpneFlXUTBOelkxT1dWaVpEUTJNbVJpTXpsbVlUTTBNRFprTUdZelpHSTJNVFkwWTJZMVpqRmhNVGRrWWpZNE16Y3paVFl4WkRRM1pXVmtNekUwTXpreVpHWm1ZbVU1WXpKa00yRTFPRGsxTkRBNE1tTXhNMkk1Wm1ZM056SXpaVEE1WWpjMVpXSmhZakl6Tm1FMU1EUTVPV1k0TkNJc0luUnBiV1Z6ZEdGdGNDSTZNVGMxTVRVME9UYzFOalUwTUgwPSIsImhpZGRlbkVsZW1lbnRzIjpbXSwic291cmNlIjpudWxsfQ%3D%3D&devMode=true&language=en&booking=eyJ0eXBlIjoidXNlci1pbnB1dCIsImxvY2F0b3IiOiJ0ZXN0IiwiZXh0ZXJuYWxDaGFubmVsSWQiOjAsInBsYXRmb3JtIjoiT3Ryb3MiLCJib29raW5nRGF0YSI6eyJmaXJzdE5hbWUiOiJURVNUIiwibGFzdE5hbWUiOiJURVNUIiwiZW1haWwiOiJmcmFuY2lzY28uY29zdGlsbG9AaG90ZWx2ZXJzZS50ZWNoIiwiY2hlY2tJbiI6IjIwMjUtMTAtMTAiLCJjaGVja091dCI6IjIwMjUtMTAtMTUiLCJodlJvb21UeXBlIjo2MzIsIm9jY3VwYW5jeSI6eyJhZHVsdHMiOjIsImNoaWxkcmVuIjowLCJjaGlsZEFnZXMiOltdLCJpbmZhbnRzIjowLCJjdXJyZW5jeSI6IiJ9LCJleHRlcm5hbENoYW5uZWxJZCI6MCwiaXNPd25Ib3RlbCI6ZmFsc2V9fQ%3D%3D',
  type: 'iframe' as const,
  iframe: {
    width: '100%',
    height: '800px',
    frameBorder: 0,
    allowFullScreen: true,
    title: 'Choose your room number - Interactive Hotel Map',
  },
}

export const specialOffers = [
  {
    id: 1,
    title: 'All inclusive package',
    description: 'Enjoy unlimited access to all amenities, meals and beverages.',
    image:
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1980&q=80',
    price: 50,
    type: 'perPerson' as const,
  },
  {
    id: 2,
    title: 'Spa Access',
    description: 'Enjoy a day of relaxation at our luxury spa - select your preferred date.',
    image:
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    price: 50,
    type: 'perPerson' as const,
    requiresDateSelection: true,
    allowsMultipleDates: true,
  },
  {
    id: 3,
    title: 'Airport Transfer',
    description: 'Convenient transportation to and from the airport (uses reservation person count).',
    image:
      'https://images.unsplash.com/photo-1563720223185-11003d516935?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    price: 35,
    type: 'perPerson' as const,
  },
  {
    id: 4,
    title: 'Gourmet Dinner',
    description: 'Exquisite dinner at our award-winning restaurant - choose your dining date.',
    image:
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    price: 60,
    type: 'perPerson' as const,
    requiresDateSelection: true,
    allowsMultipleDates: true,
  },
  {
    id: 5,
    title: 'VIP Balinese bed',
    description: 'Luxurious traditional Balinese bed setup with premium bedding and aromatherapy.',
    image:
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2049&q=80',
    price: 100,
    type: 'perPerson' as const,
    requiresDateSelection: true,
    allowsMultipleDates: true,
  },
  {
    id: 6,
    title: 'Wellness Classes',
    description: 'Join our daily wellness activities - select multiple class dates.',
    image:
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    price: 25,
    type: 'perPerson' as const,
    requiresDateSelection: true,
    allowsMultipleDates: true,
  },
]

// Language translations
export const translations = {
  en: {
    roomTitle: 'Choose your Superior Room!',
    roomSubtitle: 'Choose from our selection of premium rooms and suites',
    customizeTitle: 'Customize Your Stay',
    customizeSubtitle: 'Personalize your room for the perfect experience',
    offersTitle: 'Enhance your stay',
    offersSubtitle: 'Enhance your stay with these exclusive offers',
    emptyCartMessage: 'Select a room and customize your stay to see your booking summary here.',
    errorMessage: 'Sorry, there was an error loading the booking information. Please try again later.',
    confirmationMessage: 'Thank you for your booking! A confirmation email will be sent shortly.',
    totalLabel: 'Total',
    currencySymbol: '€',
    selectText: 'Select',
    selectedText: 'Selected',
    nightText: 'night',
    learnMoreText: 'Learn More',
    priceInfoText: 'Price includes all taxes and fees',
    makeOfferText: 'Make Offer',
    proposePriceText: 'Propose your price:',
    availabilityText: 'Subject to availability',
    offerMadeText: 'You have proposed ${price} EUR per night',
    bidSubmittedText: 'Bid submitted',
    updateBidText: 'Update bid',
    cancelBidText: 'Cancel',

    // New texts for RoomCustomization
    improveText: 'Upgrade',
    pricePerNightText: 'EUR/night',
    featuresText: 'Features and benefits',
    understood: 'Got it',
    addForPriceText: 'Add for',
    availableOptionsText: 'Available Options:',
    removeText: 'Remove',
    showMoreText: 'Show More',
    showLessText: 'Show Less',
    // New texts for compatibility system
    optionDisabledText: 'Not Available',
    conflictWithText: 'Conflicts with',
    keepCurrentText: 'Keep Current Selection',
    switchToNewText: 'Switch to New Option',
    conflictDialogTitle: 'Option Conflict',
    conflictDialogDescription: 'These options cannot be selected together. Please choose which one to keep.',

    // Section info texts
    bedsInfoText:
      'Choose the type of bed you prefer for your stay. Each option offers different levels of comfort and space according to your needs. King-size beds are ideal for couples who want more space, while twin beds are perfect for friends or family.',
    // roomSizeInfoText:
    //   'Select the room size that best fits your needs. Larger rooms provide more space and comfort, while standard rooms offer great value. Room size affects the overall comfort and available amenities.',
    locationInfoText:
      'The location of your room can significantly affect your experience. Corner rooms offer more privacy, while suites with sea views provide impressive ocean panoramas. Choose the location that best suits your preferences.',
    featuresInfoText:
      'Choose special room features that enhance your stay. From accessible accommodations to family-friendly amenities, each feature is designed to meet specific guest needs and preferences.',
    orientationInfoText:
      'Room orientation determines the natural light and views you\'ll enjoy throughout the day. Morning sun rooms are perfect for early risers, while all-day sun rooms offer maximum brightness.',
    // bestChoiceInfoText:
    //   'Select the option that best matches your travel purpose. Whether you\'re here for business, romance, or family time, we have the perfect room configuration for your needs.',
    viewInfoText:
      "Select the exact view from your room. Each option offers a unique perspective of the hotel's surroundings, from panoramic city views to impressive sunrises over the sea.",
    floorInfoText:
      'The floor where your room is located can influence the view, noise level, and accessibility. Upper floors offer better views and less noise, while lower floors provide quicker access to hotel facilities.',
    distributionInfoText:
      'Choose how your room is distributed and what amenities are included. Each option offers different space configurations and access to specific hotel features like gardens, pools, or additional living areas.',
    bedsTitle: 'Beds',
    // roomSizeTitle: 'Room Size',
    locationTitle: 'Location',
    floorTitle: 'Floor',
    distributionTitle: 'Distribution',
    featuresTitle: 'Features',
    orientationTitle: 'Orientation',
    // bestChoiceTitle: 'Best Choice for',
    viewTitle: 'View',
    exactViewTitle: 'Exact View',

    // Updated translation props for SpecialOffers (using new labels structure)
    specialOffersLabels: {
      perStay: 'per stay',
      perPerson: 'per person',
      perNight: 'per night',
      total: 'Total',
      bookNow: 'Book Now',
      numberOfPersons: 'Number of Persons',
      numberOfNights: 'Number of Nights',
      addedLabel: 'Added',
      popularLabel: 'Popular',
      personsTooltip: 'Number of persons for this offer',
      personsSingularUnit: 'person',
      personsPluralUnit: 'persons',
      nightsTooltip: 'Number of nights for this offer',
      nightsSingularUnit: 'night',
      nightsPluralUnit: 'nights',
      personSingular: 'person',
      personPlural: 'people',
      nightSingular: 'night',
      nightPlural: 'nights',
      removeOfferLabel: 'Remove Offer',
      decreaseQuantityLabel: 'Decrease Quantity',
      increaseQuantityLabel: 'Increase Quantity',
      selectDateLabel: 'Select Date',
      selectDateTooltip: 'Choose a date for this offer',
      dateRequiredLabel: 'Date required',
    },

    // PricingSummaryPanel labels
    selectedRoomLabel: 'Selected Room',
    upgradesLabel: 'Upgrades',
    specialOffersLabel: 'Special Offers',
    chooseYourSuperiorRoomLabel: 'Choose Your Superior Room',
    customizeYourRoomLabel: 'Customize Your Room',
    enhanceYourStayLabel: 'Enhance Your Stay',
    chooseYourRoomLabel: 'Choose Your Room',
    subtotalLabel: 'Subtotal',
    taxesLabel: 'Taxes',
    payAtHotelLabel: 'Pay at Hotel',
    viewTermsLabel: 'View Terms & Conditions',
    confirmButtonLabel: 'Confirm Booking',
    noUpgradesSelectedLabel: 'No upgrades selected',
    noOffersSelectedLabel: 'No offers selected',
    editLabel: 'Edit',
    roomRemovedMessage: 'Room removed from your booking',
    offerRemovedMessagePrefix: 'Offer ',
    customizationRemovedMessagePrefix: 'Customization ',
    addedMessagePrefix: 'Added: ',
    euroSuffix: ' EUR',
    loadingLabel: 'Loading...',
    checkInLabel: 'Check-in',
    checkOutLabel: 'Check-out',
    occupancyLabel: 'Occupancy',
    reservationCodeLabel: 'Reservation Code',

    // UI text
    backToHomeLabel: 'Back to Home',
    tryAgainLabel: 'Try Again',
    bookingConfirmedTitle: 'Booking Confirmed!',
    errorTitle: 'Error',
    summaryButtonLabel: 'Summary',
    removeRoomUpgradeLabel: 'Remove Room Upgrade',
    exploreLabel: 'Explore',
    roomImageAltText: 'Room image',
    fromLabel: 'From',
    customizeStayTitle: 'Customize Your Stay',
    chooseOptionsSubtitle: 'Choose your preferred options',

    // Multi-booking labels
    multiBookingLabels: {
      multiRoomBookingsTitle: 'Multi-Room Bookings',
      roomsCountLabel: 'rooms',
      singleRoomLabel: 'room',
      clickToExpandLabel: 'Click to expand/collapse',
      selectedRoomLabel: 'Selected Room',
      upgradesLabel: 'Upgrades',
      specialOffersLabel: 'Special Offers',
      chooseYourSuperiorRoomLabel: 'Choose Your Superior Room',
      customizeYourRoomLabel: 'Customize Your Room',
      enhanceYourStayLabel: 'Enhance Your Stay',
      chooseYourRoomLabel: 'Choose Your Room',
      roomTotalLabel: 'Room Total',
      subtotalLabel: 'Subtotal',
      taxesLabel: 'Taxes (10%)',
      totalLabel: 'Total',
      payAtHotelLabel: 'Payment will be made at the hotel',
      viewTermsLabel: 'View Terms & Conditions',
      confirmAllButtonLabel: 'Confirm All Bookings',
      confirmingAllLabel: 'Confirming...',
      editLabel: 'Edit',
      addLabel: 'Add',
      addUpgradeTitle: 'Add Room Upgrade',
      addSpecialOfferTitle: 'Add Special Offer',
      noUpgradesSelectedLabel: 'No upgrades selected',
      noOffersSelectedLabel: 'No special offers selected',
      noMoreUpgradesLabel: 'No more upgrades available',
      noMoreOffersLabel: 'No more offers available',
      euroSuffix: ' EUR',
      nightsLabel: 'nights',
      nightLabel: 'night',
      guestsLabel: 'guests',
      guestLabel: 'guest',
      roomImageAltText: 'Room image',
      removedSuccessfully: 'removed successfully',
      addedSuccessfully: 'added successfully',
      cannotRemoveRoom: 'Cannot remove room booking',
      itemAlreadyAdded: 'This item has already been added',
      notificationsLabel: 'Notifications',
      closeNotificationLabel: 'Close notification',
    },
  },
  es: {
    roomTitle: 'Elige tu Habitación Superior!',
    roomSubtitle: 'Elige entre nuestra selección de habitaciones y suites premium',
    customizeTitle: 'Personaliza Tu Estancia',
    customizeSubtitle: 'Personaliza tu habitación para una experiencia perfecta',
    offersTitle: 'Mejora tu estancia',
    offersSubtitle: 'Mejora tu estancia con estas ofertas exclusivas',
    emptyCartMessage: 'Selecciona una habitación y personaliza tu estancia para ver el resumen de tu reserva aquí.',
    errorMessage:
      'Lo sentimos, hubo un error al cargar la información de la reserva. Por favor, inténtalo de nuevo más tarde.',
    confirmationMessage: '¡Gracias por tu reserva! Se enviará un correo de confirmación en breve.',
    totalLabel: 'Total',
    currencySymbol: '€',
    selectText: 'Seleccionar',
    selectedText: 'Seleccionado',
    nightText: 'noche',
    learnMoreText: 'Saber Más',
    priceInfoText: 'El precio incluye todos los impuestos y tarifas',
    makeOfferText: 'Hacer Oferta',
    proposePriceText: 'Propón tu precio:',
    availabilityText: 'Sujeto a disponibilidad',
    offerMadeText: 'Has propuesto ${price} EUR por noche',
    bidSubmittedText: 'Oferta enviada',
    updateBidText: 'Actualizar oferta',
    cancelBidText: 'Cancelar',

    // New texts for RoomCustomization
    improveText: 'Mejorar',
    pricePerNightText: 'EUR/noche',
    featuresText: 'Características y ventajas',
    understood: 'Entendido',
    addForPriceText: 'Añadir por',
    availableOptionsText: 'Opciones Disponibles:',
    removeText: 'Quitar',
    showMoreText: 'Mostrar Más',
    showLessText: 'Mostrar Menos',
    // New texts for compatibility system
    optionDisabledText: 'No Disponible',
    conflictWithText: 'Conflicto con',
    keepCurrentText: 'Mantener Selección Actual',
    switchToNewText: 'Cambiar a Nueva Opción',
    conflictDialogTitle: 'Conflicto de Opciones',
    conflictDialogDescription: 'Estas opciones no pueden seleccionarse juntas. Por favor elige cuál mantener.',

    // Section info texts
    bedsInfoText:
      'Elige el tipo de cama que prefieras para tu estancia. Cada opción ofrece diferentes niveles de comodidad y espacio según tus necesidades. Las camas king-size son ideales para parejas que desean más espacio, mientras que las camas individuales son perfectas para amigos o familiares.',
    // roomSizeInfoText:
    //   'Selecciona el tamaño de la habitación que mejor se adapte a tus necesidades. Las habitaciones más grandes proporcionan más espacio y comodidad, mientras que las habitaciones estándar ofrecen un gran valor. El tamaño de la habitación afecta la comodidad general y las comodidades disponibles.',
    locationInfoText:
      'La ubicación de tu habitación puede afectar significativamente tu experiencia. Las habitaciones en esquina ofrecen más privacidad, mientras que las suites con vista al mar te brindan panoramas impresionantes del océano. Elige la ubicación que mejor se adapte a tus preferencias.',
    featuresInfoText:
      'Elige las características especiales de la habitación que mejoran tu estancia. Desde acomodaciones accesibles hasta comodidades para familias, cada característica está diseñada para satisfacer las necesidades y preferencias específicas de los huéspedes.',
    orientationInfoText:
      'La orientación de la habitación determina la luz natural y las vistas que disfrutarás a lo largo del día. Las habitaciones con sol de la mañana son perfectas para los que se levantan temprano, mientras que las habitaciones con sol de todo el día ofrecen la máxima luminosidad.',
    // bestChoiceInfoText:
    //   'Selecciona la opción que mejor coincida con tu propósito de viaje. Ya sea para negocios, romántico o tiempo de familia, tenemos la configuración de habitación perfecta para tus necesidades.',
    viewInfoText:
      'Selecciona la vista exacta desde tu habitación. Cada opción ofrece una perspectiva única del entorno del hotel, desde vistas panorámicas de la ciudad hasta impresionantes amaneceres sobre el mar.',
    floorInfoText:
      'El piso en el que se encuentra tu habitación puede influir en la vista, el ruido y la accesibilidad. Los pisos superiores ofrecen mejores vistas y menos ruido, mientras que los pisos inferiores proporcionan un acceso más rápido a las instalaciones del hotel.',
    distributionInfoText:
      'Elige cómo se distribuye tu habitación y qué comodidades están incluidas. Cada opción ofrece diferentes configuraciones de espacio y acceso a características específicas del hotel como jardines, piscinas o áreas de estar adicionales.',
    bedsTitle: 'Camas',
    // roomSizeTitle: 'Tamaño de la Habitación',
    locationTitle: 'Ubicación',
    floorTitle: 'Piso',
    distributionTitle: 'Distribución',
    featuresTitle: 'Características',
    orientationTitle: 'Orientación',
    // bestChoiceTitle: 'Mejor Opción para',
    viewTitle: 'Vista',
    exactViewTitle: 'Vista Exacta',

    // Updated translation props for SpecialOffers (using new labels structure)
    specialOffersLabels: {
      perStay: 'por estancia',
      perPerson: 'por persona',
      perNight: 'por noche',
      total: 'Total',
      bookNow: 'Reservar Ahora',
      numberOfPersons: 'Número de Personas',
      numberOfNights: 'Número de Noches',
      addedLabel: 'Añadido',
      popularLabel: 'Popular',
      personsTooltip: 'Número de personas para esta oferta',
      personsSingularUnit: 'persona',
      personsPluralUnit: 'personas',
      nightsTooltip: 'Número de noches para esta oferta',
      nightsSingularUnit: 'noche',
      nightsPluralUnit: 'noches',
      personSingular: 'persona',
      personPlural: 'personas',
      nightSingular: 'noche',
      nightPlural: 'noches',
      removeOfferLabel: 'Eliminar Oferta',
      decreaseQuantityLabel: 'Disminuir Cantidad',
      increaseQuantityLabel: 'Aumentar Cantidad',
      selectDateLabel: 'Seleccionar Fecha',
      selectDateTooltip: 'Elige una fecha para esta oferta',
      dateRequiredLabel: 'Fecha requerida',
    },

    // PricingSummaryPanel labels
    selectedRoomLabel: 'Habitación Seleccionada',
    upgradesLabel: 'Mejoras',
    specialOffersLabel: 'Ofertas Especiales',
    chooseYourSuperiorRoomLabel: 'Elige Tu Habitación Superior',
    customizeYourRoomLabel: 'Personaliza Tu Habitación',
    enhanceYourStayLabel: 'Mejora Tu Estancia',
    chooseYourRoomLabel: 'Elige Tu Habitación',
    subtotalLabel: 'Subtotal',
    taxesLabel: 'Impuestos',
    payAtHotelLabel: 'Pagar en el Hotel',
    viewTermsLabel: 'Ver Términos y Condiciones',
    confirmButtonLabel: 'Confirmar Reserva',
    noUpgradesSelectedLabel: 'No hay mejoras seleccionadas',
    noOffersSelectedLabel: 'No hay ofertas seleccionadas',
    editLabel: 'Editar',
    roomRemovedMessage: 'Habitación eliminada de tu reserva',
    offerRemovedMessagePrefix: 'Oferta ',
    customizationRemovedMessagePrefix: 'Personalización ',
    addedMessagePrefix: 'Añadido: ',
    euroSuffix: ' EUR',
    loadingLabel: 'Cargando...',
    checkInLabel: 'Fecha de Entrada',
    checkOutLabel: 'Fecha de Salida',
    occupancyLabel: 'Ocupación',
    reservationCodeLabel: 'Código de Reserva',

    // UI text
    backToHomeLabel: 'Volver a Inicio',
    tryAgainLabel: 'Intentar de Nuevo',
    bookingConfirmedTitle: '¡Reserva Confirmada!',
    errorTitle: 'Error',
    summaryButtonLabel: 'Resumen',
    removeRoomUpgradeLabel: 'Eliminar Mejora de Habitación',
    exploreLabel: 'Explorar',
    roomImageAltText: 'Imagen de habitación',
    fromLabel: 'Desde',
    customizeStayTitle: 'Personaliza Tu Estancia',
    chooseOptionsSubtitle: 'Elige las opciones que prefieras',

    // Multi-booking labels
    multiBookingLabels: {
      multiRoomBookingsTitle: 'Reservas de Múltiples Habitaciones',
      roomsCountLabel: 'habitaciones',
      singleRoomLabel: 'habitación',
      clickToExpandLabel: 'Haz clic para expandir/colapsar',
      selectedRoomLabel: 'Habitación Seleccionada',
      upgradesLabel: 'Mejoras',
      specialOffersLabel: 'Ofertas Especiales',
      chooseYourSuperiorRoomLabel: 'Elige Tu Habitación Superior',
      customizeYourRoomLabel: 'Personaliza Tu Habitación',
      enhanceYourStayLabel: 'Mejora Tu Estancia',
      chooseYourRoomLabel: 'Elige Tu Habitación',
      roomTotalLabel: 'Total de la Habitación',
      subtotalLabel: 'Subtotal',
      taxesLabel: 'Impuestos (10%)',
      totalLabel: 'Total',
      payAtHotelLabel: 'El pago se realizará en el hotel',
      viewTermsLabel: 'Ver Términos y Condiciones',
      confirmAllButtonLabel: 'Confirmar Todas las Reservas',
      confirmingAllLabel: 'Confirmando...',
      editLabel: 'Editar',
      addLabel: 'Añadir',
      addUpgradeTitle: 'Añadir Mejora de Habitación',
      addSpecialOfferTitle: 'Añadir Oferta Especial',
      noUpgradesSelectedLabel: 'No hay mejoras seleccionadas',
      noOffersSelectedLabel: 'No hay ofertas especiales seleccionadas',
      noMoreUpgradesLabel: 'No hay más mejoras disponibles',
      noMoreOffersLabel: 'No hay más ofertas disponibles',
      euroSuffix: ' EUR',
      nightsLabel: 'noches',
      nightLabel: 'noche',
      guestsLabel: 'huéspedes',
      guestLabel: 'huésped',
      roomImageAltText: 'Imagen de habitación',
      removedSuccessfully: 'eliminado exitosamente',
      addedSuccessfully: 'añadido exitosamente',
      cannotRemoveRoom: 'No se puede eliminar la reserva de habitación',
      itemAlreadyAdded: 'Este elemento ya ha sido añadido',
      notificationsLabel: 'Notificaciones',
      closeNotificationLabel: 'Cerrar notificación',
    },
  },
}

// Section configurations for RoomCustomization
export const getSectionsConfig = (lang: 'en' | 'es') => {
  const texts = translations[lang]
  return [
    {
      key: 'camas',
      title: texts.bedsTitle || 'Camas',
      icon: Bed,
      hasModal: true,
      hasFeatures: false,
      infoText: texts.bedsInfoText,
    },
    // {
    //   key: 'roomSize',
    //   title: texts.roomSizeTitle || 'Room Size',
    //   icon: Home,
    //   hasModal: true,
    //   hasFeatures: false,
    //   infoText: texts.roomSizeInfoText,
    // },
    {
      key: 'distribucion',
      title: texts.distributionTitle || 'Distribución',
      icon: Package,
      hasModal: true,
      hasFeatures: false,
      infoText: texts.distributionInfoText,
    },
    {
      key: 'features',
      title: texts.featuresTitle || 'Features',
      icon: Users,
      hasModal: true,
      hasFeatures: false,
      infoText: texts.featuresInfoText,
    },
    {
      key: 'orientation',
      title: texts.orientationTitle || 'Orientation',
      icon: Compass,
      hasModal: true,
      hasFeatures: false,
      infoText: texts.orientationInfoText,
    },
    // {
    //   key: 'bestChoice',
    //   title: texts.bestChoiceTitle || 'Best Choice for',
    //   icon: Heart,
    //   hasModal: true,
    //   hasFeatures: false,
    //   infoText: texts.bestChoiceInfoText,
    // },
    {
      key: 'vista',
      title: (texts.viewTitle || 'Vista').replace('exacta', '').trim(),
      icon: Waves,
      hasModal: false,
      hasFeatures: false,
      infoText: texts.viewInfoText,
    },
    {
      key: 'ubicacion',
      title: texts.locationTitle || 'Ubicación',
      icon: Hotel,
      hasModal: true,
      hasFeatures: false,
      infoText: texts.locationInfoText,
    },
    {
      key: 'vistaExacta',
      title: texts.exactViewTitle || 'Vista exacta',
      icon: Eye,
      hasModal: false,
      hasFeatures: false,
      infoText: texts.viewInfoText,
    },
  ]
}

// Mock data for multi-booking scenarios
export const mockRoomBookings = [
  {
    id: 'booking-1',
    roomName: 'Deluxe Room',
    roomNumber: '201',
    guestName: 'John Smith',
    checkIn: '10/10/2025',
    checkOut: '15/10/2025',
    guests: 2,
    nights: 4,
    payAtHotel: true,
    roomImage:
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    items: [
      { id: 'room-1', name: 'Deluxe Room', price: 129.99, type: 'room' as const },
      { id: 'breakfast-1', name: 'Breakfast Package', price: 15.0, type: 'offer' as const },
      { id: 'ocean-view-1', name: 'Ocean View', price: 45.0, type: 'customization' as const },
    ],
  },
  {
    id: 'booking-2',
    roomName: 'Premium Room',
    roomNumber: '305',
    guestName: 'Sarah Johnson',
    checkIn: '10/10/2025',
    checkOut: '15/10/2025',
    guests: 3,
    nights: 4,
    payAtHotel: false,
    roomImage:
      'https://images.unsplash.com/photo-1595576508898-0ad5c879a061?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
    items: [
      { id: 'room-2', name: 'Premium Room', price: 199.99, type: 'room' as const },
      { id: 'spa-2', name: 'Spa Access', price: 50.0, type: 'offer' as const },
      { id: 'king-bed-2', name: 'King Bed', price: 30.0, type: 'customization' as const },
      { id: 'poolside-2', name: 'Poolside', price: 25.0, type: 'customization' as const },
    ],
  },
  {
    id: 'booking-3',
    roomName: 'Executive Suite',
    roomNumber: '501',
    guestName: 'Michael Davis',
    checkIn: '10/10/2025',
    checkOut: '15/10/2025',
    guests: 2,
    nights: 4,
    payAtHotel: true,
    roomImage:
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
    items: [
      { id: 'room-3', name: 'Executive Suite', price: 299.99, type: 'room' as const },
      { id: 'dinner-3', name: 'Gourmet Dinner', price: 60.0, type: 'offer' as const },
      { id: 'transfer-3', name: 'Airport Transfer', price: 35.0, type: 'offer' as const },
      { id: 'high-floor-3', name: 'High Floor (5+)', price: 30.0, type: 'customization' as const },
    ],
  },
]

// Available items for adding to rooms
export const mockAvailableUpgrades = [
  { id: 'king-bed', name: 'King Bed', price: 30, category: 'Beds' },
  { id: 'ocean-view', name: 'Ocean View', price: 45, category: 'View' },
  { id: 'poolside', name: 'Poolside', price: 25, category: 'Location' },
  { id: 'high-floor', name: 'High Floor (5+)', price: 30, category: 'Floor' },
]

export const mockAvailableOffers = [
  { id: 'breakfast', name: 'Breakfast Package', price: 15, category: 'Dining' },
  { id: 'spa', name: 'Spa Access', price: 50, category: 'Wellness' },
  { id: 'transfer', name: 'Airport Transfer', price: 35, category: 'Transport' },
  { id: 'dinner', name: 'Gourmet Dinner', price: 60, category: 'Dining' },
  { id: 'laundry', name: 'Laundry Service', price: 20, category: 'Services' },
]

// Section options for RoomCustomization
export const sectionOptions = {
  camas: bedsOptions,
  // roomSize: roomSizeOptions,
  distribucion: distributionOptions,
  features: featuresOptions,
  orientation: orientationOptions,
  // bestChoice: bestChoiceOptions,
  vista: viewOptions, // Simple views without images
  ubicacion: locationOptions,
  vistaExacta: exactViewOptions, // Exact views with images
}

// Export compatibility rules for easy import
export { defaultCompatibilityRules } from '../ABS_RoomCustomization/compatibilityRules'
