import { Bed, Building2, Hotel, Waves } from 'lucide-react'

// Mock data for ABS_Landing stories
export const roomOptions = [
  {
    id: 'deluxe',
    name: 'DELUXE GOLD',
    description: 'True rock stars look down from above. A space covering 33 square metres with spectacular sea views, a private furnished terrace and elegant décor for a superior experience from the fifth floor upwards. Exceed even your own expectations, and relax with chromotherapy lighting that you can personalise. Lie back like a rock star in a luxurious king-sized bed, or in two full-sized single beds, and enjoy this room\'s ultra-modern facilities: thoughtfully selected state-of-the-art furniture, a 43 SMART TV screen, a dock station and a comfortable reading corner with a sofa bed.',
    price: 129.99,
    perNight: true,
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/c37cc822-a6bf-4345-93f8-deb22d186d10/image.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/49a54c09-0945-4a87-893d-8d28d79e0f5b/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/9d29265c-3fc9-4c70-b953-7e3335f200aa/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/61c2250a-8967-446e-91b4-2bc50bf9be1a/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '30 to 35 m2 / 325 to 375 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Desk',
      'Hairdryer',
      'In Main Building',
      'Iron & Board',
      'Landmark View',
      'Magnifying mirror',
      'Minibar',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Shoe kit',
      'Smart TV',
      'Table and chairs set',
      'Tea Set'
    ],
  },
  {
    id: 'premium',
    name: 'DELUXE SWIM-UP',
    description: 'What about adding to your Double room a furnished outdoors terrace with a direct access to the meandering pool and private sun lounger waiting for you to enjoy the splash.',
    price: 199.99,
    oldPrice: 249.99,
    perNight: true,
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt634/cdf69769-f553-4c82-aa06-e3e8867954fb/image.webp',
    images: [
        'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt634/cdf69769-f553-4c82-aa06-e3e8867954fb/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt634/c46d320b-89d6-4975-9af0-febbeaf4b450/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '30 to 35 m2 / 325 to 375 sqft',
      'AC',
      'Afternoon Sun',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Desk',
      'Hairdryer',
      'Iron & Board',
      'Magnifying mirror',
      'Minibar',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Piazza View',
      'Pillow Menu',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Shared Pool',
      'Shoe kit',
      'Smart TV',
      'Table and chairs set',
      'Tea Set',
      'Terrace'
    ],
  },
  {
    id: 'rocksuite',
    name: 'ROCK SUITE',
    description: 'Our contemporary Hard Rock Ibiza Suites perfectly capture the authenticity and irreverence of rock \'n\' roll with the sensuality and sophistication of Ibiza Island. Three connecting spaces - Living/ lounge, bedroom and bathroom - allowing you to decide when it\'s time for plugging in or chilling out. Totally unpredictable, totally Ibiza Hard Rock.',
    price: 449.99,
    oldPrice: 549.99,
    perNight: true,
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/3e7e2260-63e3-4934-9358-ebf08bb6d96a/image.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/3e7e2260-63e3-4934-9358-ebf08bb6d96a/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/cb767423-cda2-4345-9008-dd1a42573ead/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/04386083-34f1-4175-8379-685ae5071a12/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '60 to 70 m2 / 645 to 755 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Coffee Machine',
      'Desk',
      'Hairdryer',
      'Hydromassage Bathtub',
      'Iron & Board',
      'Landmark View',
      'Lateral Streets View',
      'Living Room',
      'Magnifying mirror',
      'Minibar',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Pool View',
      'Premium Wi-Fi',
      'Rain shower',
      'Recyclables Coffee Capsules',
      'Safe',
      'Shoe kit',
      'Smart TV',
      'Sofa Bed - Double',
      'Table and chairs set',
      'Tea Set'
    ],
  },
  {
    id: '80s-suite',
    name: '80S SUITE',
    description: '60 square-meter space with an 80s setting, among which vinyl, mirror ball, music cassettes with 80s music and some 80\'s gifts like a welcome kit that includes a t-shirt.',
    price: 399.99,
    oldPrice: 499.99,
    perNight: true,
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt635/24fa2b9d-307c-4d23-9021-eb174520dbc0/image.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt641/850e6840-cc2b-48f8-9059-3a64d2b9b097/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt641/f356e89d-6dca-443e-9ac4-9bb975a84b07/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt641/e69fa285-5242-4992-831b-7e67d401ba00/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '60 to 70 m2 / 645 to 755 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Coffee Machine',
      'Desk',
      'Hairdryer',
      'Hydromassage Bathtub',
      'Iron & Board',
      'King Size Bed',
      'Landmark View',
      'Living Room',
      'Magnifying mirror',
      'Minibar',
      'Morning Sun',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Pool View',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Smart TV',
      'Sofa Bed - Double',
      'Shoe kit',
      'Table and chairs set',
      'Tea Set'
    ],
  },
]

export const bedsOptions = [
  {
    id: 'twin',
    name: 'Twin Beds',
    description: 'Two separate single beds',
    price: 0,
    icon: 'bed',
    label: 'Twin Beds',
  },
  {
    id: 'queen',
    name: 'Queen Bed',
    description: 'One large queen-sized bed',
    price: 15,
    icon: 'bed',
    label: 'Queen Bed',
  },
  {
    id: 'king',
    name: 'King Bed',
    description: 'One extra-large king-sized bed',
    price: 30,
    icon: 'bed',
    label: 'King Bed',
  },
]

export const locationOptions = [
  {
    id: 'standard',
    name: 'Standard View',
    description: 'Basic room with no specific view',
    price: 0,
    icon: 'building',
    label: 'Standard View',
  },
  {
    id: 'poolside',
    name: 'Poolside',
    description: 'Room near the swimming pool',
    price: 25,
    icon: 'waves',
    label: 'Poolside',
  },
  {
    id: 'oceanview',
    name: 'Ocean View',
    description: 'Room with a beautiful ocean view',
    price: 50,
    icon: 'corner-up-right',
    label: 'Ocean View',
  },
]

export const floorOptions = [
  {
    id: 'ground',
    name: 'Ground Floor',
    description: 'Easy access, no stairs or elevator needed',
    price: 0,
    icon: 'home',
    label: 'Ground Floor',
  },
  {
    id: 'mid',
    name: 'Middle Floors (2-4)',
    description: 'Balance between view and accessibility',
    price: 15,
    icon: 'layout',
    label: 'Middle Floors (2-4)',
  },
  {
    id: 'high',
    name: 'High Floor (5+)',
    description: 'Best views but requires elevator',
    price: 30,
    icon: 'layers',
    label: 'High Floor (5+)',
  },
]

export const viewOptions = [
  {
    id: 'interior',
    name: 'Interior',
    description: 'Room facing the interior courtyard',
    price: 0,
    icon: 'arrow-up',
    label: 'Interior View',
    imageUrl:
      'https://hvdatauatstgweu.blob.core.windows.net/roommediaimages/h83/r18015/outside/5a6470e5-65cc-46a5-bc84-1ac0f73789bf/image_c.webp',
  },
  {
    id: 'street',
    name: 'Street View',
    description: 'Room with a view of the street',
    price: 10,
    icon: 'corner-up-right',
    label: 'Street View',
    imageUrl:
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
  },
  {
    id: 'ocean',
    name: 'Ocean View',
    description: 'Room with ocean view',
    price: 45,
    icon: 'waves',
    label: 'Ocean View',
    imageUrl:
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1064&q=80',
  },
]

export const roomSelectionMap = {
  id: 'room-selection',
  title: 'Choose your room number.',
  description: 'Explore the hotel and choose the exact room where you want to stay.',
  url: 'https://map-uat.hotelverse.tech/Webmap/en/ChooseYourRoom?config=eyJjbGllbnRJZCI6MSwiaG90ZWxJZCI6ODMsImN1cnJlbmN5IjoiRVVSIiwiYWNjZXNzVG9rZW5IViI6ImV5SnphV2R1WVhSMWNtVWlPaUk0TWpSbU5EUmtaakZqWXpneFlXUTBOelkxT1dWaVpEUTJNbVJpTXpsbVlUTTBNRFprTUdZelpHSTJNVFkwWTJZMVpqRmhNVGRrWWpZNE16Y3paVFl4WkRRM1pXVmtNekUwTXpreVpHWm1ZbVU1WXpKa00yRTFPRGsxTkRBNE1tTXhNMkk1Wm1ZM056SXpaVEE1WWpjMVpXSmhZakl6Tm1FMU1EUTVPV1k0TkNJc0luUnBiV1Z6ZEdGdGNDSTZNVGMxTVRVME9UYzFOalUwTUgwPSIsImhpZGRlbkVsZW1lbnRzIjpbXSwic291cmNlIjpudWxsfQ%3D%3D&devMode=true&language=en&booking=eyJ0eXBlIjoidXNlci1pbnB1dCIsImxvY2F0b3IiOiJ0ZXN0IiwiZXh0ZXJuYWxDaGFubmVsSWQiOjAsInBsYXRmb3JtIjoiT3Ryb3MiLCJib29raW5nRGF0YSI6eyJmaXJzdE5hbWUiOiJURVNUIiwibGFzdE5hbWUiOiJURVNUIiwiZW1haWwiOiJmcmFuY2lzY28uY29zdGlsbG9AaG90ZWx2ZXJzZS50ZWNoIiwiY2hlY2tJbiI6IjIwMjUtMTAtMTAiLCJjaGVja091dCI6IjIwMjUtMTAtMTUiLCJodlJvb21UeXBlIjo2MzIsIm9jY3VwYW5jeSI6eyJhZHVsdHMiOjIsImNoaWxkcmVuIjowLCJjaGlsZEFnZXMiOltdLCJpbmZhbnRzIjowLCJjdXJyZW5jeSI6IiJ9LCJleHRlcm5hbENoYW5uZWxJZCI6MCwiaXNPd25Ib3RlbCI6ZmFsc2V9fQ%3D%3D',
  type: 'iframe' as const,
  iframe: {
    width: '100%',
    height: '400px',
    frameBorder: 0,
    allowFullScreen: true,
    title: 'Choose your room number - Interactive Hotel Map',
  },
}

export const specialOffers = [
  {
    id: 1,
    title: 'All inclusive package',
    description: 'Enjoy unlimited access to all amenities, meals and beverages.',
    image:
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1980&q=80',
    price: 50,
    type: 'perPerson' as const,
  },
  {
    id: 2,
    title: 'Spa Access',
    description: 'Enjoy a day of relaxation at our luxury spa - select your preferred date.',
    image:
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    price: 50,
    type: 'perPerson' as const,
    requiresDateSelection: true,
  },
  {
    id: 3,
    title: 'Airport Transfer',
    description: 'Convenient transportation to and from the airport (uses reservation person count).',
    image:
      'https://images.unsplash.com/photo-1563720223185-11003d516935?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    price: 35,
    type: 'perPerson' as const,
  },
  {
    id: 4,
    title: 'Gourmet Dinner',
    description: 'Exquisite dinner at our award-winning restaurant - choose your dining date.',
    image:
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    price: 60,
    type: 'perPerson' as const,
    requiresDateSelection: true,
  },
  {
    id: 5,
    title: 'VIP Balinese bed',
    description: 'Luxurious traditional Balinese bed setup with premium bedding and aromatherapy.',
    image:
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2049&q=80',
    price: 100,
    type: 'perStay' as const,
  },
  {
    id: 6,
    title: 'Wellness Classes',
    description: 'Join our daily wellness activities - select multiple class dates.',
    image:
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    price: 25,
    type: 'perPerson' as const,
    requiresDateSelection: true,
    allowsMultipleDates: true,
  },
]

// Language translations
export const translations = {
  en: {
    roomTitle: 'Room',
    roomSubtitle: 'Choose from our selection of premium rooms and suites',
    customizeTitle: 'Customize Your Stay',
    customizeSubtitle: 'Personalize your room for the perfect experience',
    offersTitle: 'Enhance your stay',
    offersSubtitle: 'Enhance your stay with these exclusive offers',
    emptyCartMessage: 'Select a room and customize your stay to see your booking summary here.',
    errorMessage: 'Sorry, there was an error loading the booking information. Please try again later.',
    confirmationMessage: 'Thank you for your booking! A confirmation email will be sent shortly.',
    totalLabel: 'Total',
    currencySymbol: '€',
    selectText: 'Select',
    selectedText: 'Selected',
    nightText: 'night',
    learnMoreText: 'Learn More',
    priceInfoText: 'Price includes all taxes and fees',

    // New texts for RoomCustomization
    improveText: 'Upgrade',
    pricePerNightText: 'EUR/night',
    featuresText: 'Features and benefits',
    understood: 'Got it',
    addForPriceText: 'Add for',
    availableOptionsText: 'Available Options:',
    removeText: 'Remove',

    // Section info texts
    bedsInfoText:
      'Choose the type of bed you prefer for your stay. Each option offers different levels of comfort and space according to your needs. King-size beds are ideal for couples who want more space, while twin beds are perfect for friends or family.',
    locationInfoText:
      'The location of your room can significantly affect your experience. Corner rooms offer more privacy, while suites with sea views provide impressive ocean panoramas. Choose the location that best suits your preferences.',
    viewInfoText:
      "Select the exact view from your room. Each option offers a unique perspective of the hotel's surroundings, from panoramic city views to impressive sunrises over the sea.",
    floorInfoText:
      'The floor where your room is located can influence the view, noise level, and accessibility. Upper floors offer better views and less noise, while lower floors provide quicker access to hotel facilities.',
    bedsTitle: 'Beds',
    locationTitle: 'Location',
    floorTitle: 'Floor',
    viewTitle: 'Exact  View',

    // Updated translation props for SpecialOffers (using new labels structure)
    specialOffersLabels: {
      perStay: 'per stay',
      perPerson: 'per person',
      perNight: 'per night',
      total: 'Total',
      bookNow: 'Book Now',
      numberOfPersons: 'Number of Persons',
      numberOfNights: 'Number of Nights',
      addedLabel: 'Added',
      popularLabel: 'Popular',
      personsTooltip: 'Number of persons for this offer',
      personsSingularUnit: 'person',
      personsPluralUnit: 'persons',
      nightsTooltip: 'Number of nights for this offer',
      nightsSingularUnit: 'night',
      nightsPluralUnit: 'nights',
      personSingular: 'person',
      personPlural: 'people',
      nightSingular: 'night',
      nightPlural: 'nights',
      removeOfferLabel: 'Remove Offer',
      decreaseQuantityLabel: 'Decrease Quantity',
      increaseQuantityLabel: 'Increase Quantity',
      selectDateLabel: 'Select Date',
      selectDateTooltip: 'Choose a date for this offer',
      dateRequiredLabel: 'Date required',
    },

    // PricingSummaryPanel labels
    selectedRoomLabel: 'Selected Room',
    upgradesLabel: 'Upgrades',
    specialOffersLabel: 'Special Offers',
    subtotalLabel: 'Subtotal',
    taxesLabel: 'Taxes',
    payAtHotelLabel: 'Pay at Hotel',
    viewTermsLabel: 'View Terms & Conditions',
    confirmButtonLabel: 'Confirm Booking',
    noUpgradesSelectedLabel: 'No upgrades selected',
    noOffersSelectedLabel: 'No offers selected',
    editLabel: 'Edit',
    roomRemovedMessage: 'Room removed from your booking',
    offerRemovedMessagePrefix: 'Offer ',
    customizationRemovedMessagePrefix: 'Customization ',
    addedMessagePrefix: 'Added: ',
    euroSuffix: ' EUR',
    loadingLabel: 'Loading...',
    checkInLabel: 'Check-in',
    checkOutLabel: 'Check-out',
    occupancyLabel: 'Occupancy',
    reservationCodeLabel: 'Reservation Code',

    // UI text
    backToHomeLabel: 'Back to Home',
    tryAgainLabel: 'Try Again',
    bookingConfirmedTitle: 'Booking Confirmed!',
    errorTitle: 'Error',
    summaryButtonLabel: 'Summary',
    removeRoomUpgradeLabel: 'Remove Room Upgrade',
    exploreLabel: 'Explore',
    roomImageAltText: 'Room image',
    fromLabel: 'From',
    customizeStayTitle: 'Customize Your Stay',
    chooseOptionsSubtitle: 'Choose your preferred options',

    // Multi-booking labels
    multiBookingLabels: {
      multiRoomBookingsTitle: 'Multi-Room Bookings',
      roomsCountLabel: 'rooms',
      singleRoomLabel: 'room',
      clickToExpandLabel: 'Click to expand/collapse',
      selectedRoomLabel: 'Selected Room',
      upgradesLabel: 'Upgrades',
      specialOffersLabel: 'Special Offers',
      roomTotalLabel: 'Room Total',
      subtotalLabel: 'Subtotal',
      taxesLabel: 'Taxes (10%)',
      totalLabel: 'Total',
      payAtHotelLabel: 'Payment will be made at the hotel',
      viewTermsLabel: 'View Terms & Conditions',
      confirmAllButtonLabel: 'Confirm All Bookings',
      confirmingAllLabel: 'Confirming...',
      editLabel: 'Edit',
      addLabel: 'Add',
      addUpgradeTitle: 'Add Room Upgrade',
      addSpecialOfferTitle: 'Add Special Offer',
      noUpgradesSelectedLabel: 'No upgrades selected',
      noOffersSelectedLabel: 'No special offers selected',
      noMoreUpgradesLabel: 'No more upgrades available',
      noMoreOffersLabel: 'No more offers available',
      euroSuffix: ' EUR',
      nightsLabel: 'nights',
      nightLabel: 'night',
      guestsLabel: 'guests',
      guestLabel: 'guest',
      roomImageAltText: 'Room image',
      removedSuccessfully: 'removed successfully',
      addedSuccessfully: 'added successfully',
      cannotRemoveRoom: 'Cannot remove room booking',
      itemAlreadyAdded: 'This item has already been added',
      notificationsLabel: 'Notifications',
      closeNotificationLabel: 'Close notification',
    },
  },
  es: {
    roomTitle: 'Habitación',
    roomSubtitle: 'Elige entre nuestra selección de habitaciones y suites premium',
    customizeTitle: 'Personaliza Tu Estancia',
    customizeSubtitle: 'Personaliza tu habitación para una experiencia perfecta',
    offersTitle: 'Mejora tu estancia',
    offersSubtitle: 'Mejora tu estancia con estas ofertas exclusivas',
    emptyCartMessage: 'Selecciona una habitación y personaliza tu estancia para ver el resumen de tu reserva aquí.',
    errorMessage:
      'Lo sentimos, hubo un error al cargar la información de la reserva. Por favor, inténtalo de nuevo más tarde.',
    confirmationMessage: '¡Gracias por tu reserva! Se enviará un correo de confirmación en breve.',
    totalLabel: 'Total',
    currencySymbol: '€',
    selectText: 'Seleccionar',
    selectedText: 'Seleccionado',
    nightText: 'noche',
    learnMoreText: 'Saber Más',
    priceInfoText: 'El precio incluye todos los impuestos y tarifas',

    // New texts for RoomCustomization
    improveText: 'Mejorar',
    pricePerNightText: 'EUR/noche',
    featuresText: 'Características y ventajas',
    understood: 'Entendido',
    addForPriceText: 'Añadir por',
    availableOptionsText: 'Opciones Disponibles:',
    removeText: 'Quitar',

    // Section info texts
    bedsInfoText:
      'Elige el tipo de cama que prefieras para tu estancia. Cada opción ofrece diferentes niveles de comodidad y espacio según tus necesidades. Las camas king-size son ideales para parejas que desean más espacio, mientras que las camas individuales son perfectas para amigos o familiares.',
    locationInfoText:
      'La ubicación de tu habitación puede afectar significativamente tu experiencia. Las habitaciones en esquina ofrecen más privacidad, mientras que las suites con vista al mar te brindan panoramas impresionantes del océano. Elige la ubicación que mejor se adapte a tus preferencias.',
    viewInfoText:
      'Selecciona la vista exacta desde tu habitación. Cada opción ofrece una perspectiva única del entorno del hotel, desde vistas panorámicas de la ciudad hasta impresionantes amaneceres sobre el mar.',
    floorInfoText:
      'El piso en el que se encuentra tu habitación puede influir en la vista, el ruido y la accesibilidad. Los pisos superiores ofrecen mejores vistas y menos ruido, mientras que los pisos inferiores proporcionan un acceso más rápido a las instalaciones del hotel.',
    bedsTitle: 'Camas',
    locationTitle: 'Ubicación',
    floorTitle: 'Piso',
    viewTitle: 'Vista',

    // Updated translation props for SpecialOffers (using new labels structure)
    specialOffersLabels: {
      perStay: 'por estancia',
      perPerson: 'por persona',
      perNight: 'por noche',
      total: 'Total',
      bookNow: 'Reservar Ahora',
      numberOfPersons: 'Número de Personas',
      numberOfNights: 'Número de Noches',
      addedLabel: 'Añadido',
      popularLabel: 'Popular',
      personsTooltip: 'Número de personas para esta oferta',
      personsSingularUnit: 'persona',
      personsPluralUnit: 'personas',
      nightsTooltip: 'Número de noches para esta oferta',
      nightsSingularUnit: 'noche',
      nightsPluralUnit: 'noches',
      personSingular: 'persona',
      personPlural: 'personas',
      nightSingular: 'noche',
      nightPlural: 'noches',
      removeOfferLabel: 'Eliminar Oferta',
      decreaseQuantityLabel: 'Disminuir Cantidad',
      increaseQuantityLabel: 'Aumentar Cantidad',
      selectDateLabel: 'Seleccionar Fecha',
      selectDateTooltip: 'Elige una fecha para esta oferta',
      dateRequiredLabel: 'Fecha requerida',
    },

    // PricingSummaryPanel labels
    selectedRoomLabel: 'Habitación Seleccionada',
    upgradesLabel: 'Mejoras',
    specialOffersLabel: 'Ofertas Especiales',
    subtotalLabel: 'Subtotal',
    taxesLabel: 'Impuestos',
    payAtHotelLabel: 'Pagar en el Hotel',
    viewTermsLabel: 'Ver Términos y Condiciones',
    confirmButtonLabel: 'Confirmar Reserva',
    noUpgradesSelectedLabel: 'No hay mejoras seleccionadas',
    noOffersSelectedLabel: 'No hay ofertas seleccionadas',
    editLabel: 'Editar',
    roomRemovedMessage: 'Habitación eliminada de tu reserva',
    offerRemovedMessagePrefix: 'Oferta ',
    customizationRemovedMessagePrefix: 'Personalización ',
    addedMessagePrefix: 'Añadido: ',
    euroSuffix: ' EUR',
    loadingLabel: 'Cargando...',
    checkInLabel: 'Fecha de Entrada',
    checkOutLabel: 'Fecha de Salida',
    occupancyLabel: 'Ocupación',
    reservationCodeLabel: 'Código de Reserva',

    // UI text
    backToHomeLabel: 'Volver a Inicio',
    tryAgainLabel: 'Intentar de Nuevo',
    bookingConfirmedTitle: '¡Reserva Confirmada!',
    errorTitle: 'Error',
    summaryButtonLabel: 'Resumen',
    removeRoomUpgradeLabel: 'Eliminar Mejora de Habitación',
    exploreLabel: 'Explorar',
    roomImageAltText: 'Imagen de habitación',
    fromLabel: 'Desde',
    customizeStayTitle: 'Personaliza Tu Estancia',
    chooseOptionsSubtitle: 'Elige las opciones que prefieras',

    // Multi-booking labels
    multiBookingLabels: {
      multiRoomBookingsTitle: 'Reservas de Múltiples Habitaciones',
      roomsCountLabel: 'habitaciones',
      singleRoomLabel: 'habitación',
      clickToExpandLabel: 'Haz clic para expandir/colapsar',
      selectedRoomLabel: 'Habitación Seleccionada',
      upgradesLabel: 'Mejoras',
      specialOffersLabel: 'Ofertas Especiales',
      roomTotalLabel: 'Total de la Habitación',
      subtotalLabel: 'Subtotal',
      taxesLabel: 'Impuestos (10%)',
      totalLabel: 'Total',
      payAtHotelLabel: 'El pago se realizará en el hotel',
      viewTermsLabel: 'Ver Términos y Condiciones',
      confirmAllButtonLabel: 'Confirmar Todas las Reservas',
      confirmingAllLabel: 'Confirmando...',
      editLabel: 'Editar',
      addLabel: 'Añadir',
      addUpgradeTitle: 'Añadir Mejora de Habitación',
      addSpecialOfferTitle: 'Añadir Oferta Especial',
      noUpgradesSelectedLabel: 'No hay mejoras seleccionadas',
      noOffersSelectedLabel: 'No hay ofertas especiales seleccionadas',
      noMoreUpgradesLabel: 'No hay más mejoras disponibles',
      noMoreOffersLabel: 'No hay más ofertas disponibles',
      euroSuffix: ' EUR',
      nightsLabel: 'noches',
      nightLabel: 'noche',
      guestsLabel: 'huéspedes',
      guestLabel: 'huésped',
      roomImageAltText: 'Imagen de habitación',
      removedSuccessfully: 'eliminado exitosamente',
      addedSuccessfully: 'añadido exitosamente',
      cannotRemoveRoom: 'No se puede eliminar la reserva de habitación',
      itemAlreadyAdded: 'Este elemento ya ha sido añadido',
      notificationsLabel: 'Notificaciones',
      closeNotificationLabel: 'Cerrar notificación',
    },
  },
}

// Section configurations for RoomCustomization
export const getSectionsConfig = (lang: 'en' | 'es') => {
  const texts = translations[lang]
  return [
    {
      key: 'camas',
      title: texts.bedsTitle || 'Camas',
      icon: Bed,
      hasModal: true,
      hasFeatures: false,
      infoText: texts.bedsInfoText,
    },
    {
      key: 'ubicacion',
      title: texts.locationTitle || 'Ubicación',
      icon: Hotel,
      hasModal: true,
      hasFeatures: false,
      infoText: texts.locationInfoText,
    },
    {
      key: 'piso',
      title: texts.floorTitle || 'Piso',
      icon: Building2,
      hasModal: true,
      hasFeatures: true,
      infoText: texts.floorInfoText,
    },
    {
      key: 'vista',
      title: texts.viewTitle || 'Vista exacta',
      icon: Waves,
      hasModal: false,
      hasFeatures: false,
      infoText: texts.viewInfoText,
    },
  ]
}

// Mock data for multi-booking scenarios
export const mockRoomBookings = [
  {
    id: 'booking-1',
    roomName: 'Deluxe Room',
    roomNumber: '201',
    guestName: 'John Smith',
    checkIn: '01/01/2025',
    checkOut: '05/01/2025',
    guests: 2,
    nights: 4,
    payAtHotel: true,
    roomImage:
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    items: [
      { id: 'room-1', name: 'Deluxe Room', price: 129.99, type: 'room' as const },
      { id: 'breakfast-1', name: 'Breakfast Package', price: 15.0, type: 'offer' as const },
      { id: 'ocean-view-1', name: 'Ocean View', price: 45.0, type: 'customization' as const },
    ],
  },
  {
    id: 'booking-2',
    roomName: 'Premium Room',
    roomNumber: '305',
    guestName: 'Sarah Johnson',
    checkIn: '01/01/2025',
    checkOut: '05/01/2025',
    guests: 3,
    nights: 4,
    payAtHotel: false,
    roomImage:
      'https://images.unsplash.com/photo-1595576508898-0ad5c879a061?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
    items: [
      { id: 'room-2', name: 'Premium Room', price: 199.99, type: 'room' as const },
      { id: 'spa-2', name: 'Spa Access', price: 50.0, type: 'offer' as const },
      { id: 'king-bed-2', name: 'King Bed', price: 30.0, type: 'customization' as const },
      { id: 'poolside-2', name: 'Poolside', price: 25.0, type: 'customization' as const },
    ],
  },
  {
    id: 'booking-3',
    roomName: 'Executive Suite',
    roomNumber: '501',
    guestName: 'Michael Davis',
    checkIn: '01/01/2025',
    checkOut: '05/01/2025',
    guests: 2,
    nights: 4,
    payAtHotel: true,
    roomImage:
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
    items: [
      { id: 'room-3', name: 'Executive Suite', price: 299.99, type: 'room' as const },
      { id: 'dinner-3', name: 'Gourmet Dinner', price: 60.0, type: 'offer' as const },
      { id: 'transfer-3', name: 'Airport Transfer', price: 35.0, type: 'offer' as const },
      { id: 'high-floor-3', name: 'High Floor (5+)', price: 30.0, type: 'customization' as const },
    ],
  },
]

// Available items for adding to rooms
export const mockAvailableUpgrades = [
  { id: 'king-bed', name: 'King Bed', price: 30, category: 'Beds' },
  { id: 'ocean-view', name: 'Ocean View', price: 45, category: 'View' },
  { id: 'poolside', name: 'Poolside', price: 25, category: 'Location' },
  { id: 'high-floor', name: 'High Floor (5+)', price: 30, category: 'Floor' },
]

export const mockAvailableOffers = [
  { id: 'breakfast', name: 'Breakfast Package', price: 15, category: 'Dining' },
  { id: 'spa', name: 'Spa Access', price: 50, category: 'Wellness' },
  { id: 'transfer', name: 'Airport Transfer', price: 35, category: 'Transport' },
  { id: 'dinner', name: 'Gourmet Dinner', price: 60, category: 'Dining' },
  { id: 'laundry', name: 'Laundry Service', price: 20, category: 'Services' },
]

// Section options for RoomCustomization
export const sectionOptions = {
  camas: bedsOptions,
  ubicacion: locationOptions,
  piso: floorOptions,
  vista: viewOptions,
}
