import type { RoomOption } from '@/components/upsell/RoomSelectionCarousel/types'

// Mock data for ABS_Landing stories
export const roomOptions: RoomOption[] = [
  {
    id: 'deluxe',
    title: "Live luxury's pinnacle by the sea",
    roomType: 'DELUXE GOLD',
    description:
      "True rock stars look down from above. A space covering 33 square metres with spectacular sea views, a private furnished terrace and elegant décor for a superior experience from the fifth floor upwards. Exceed even your own expectations, and relax with chromotherapy lighting that you can personalise. Lie back like a rock star in a luxurious king-sized bed, or in two full-sized single beds, and enjoy this room's ultra-modern facilities: thoughtfully selected state-of-the-art furniture, a 43 SMART TV screen, a dock station and a comfortable reading corner with a sofa bed.",
    price: '22',
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/c37cc822-a6bf-4345-93f8-deb22d186d10/image.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/49a54c09-0945-4a87-893d-8d28d79e0f5b/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/9d29265c-3fc9-4c70-b953-7e3335f200aa/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt633/61c2250a-8967-446e-91b4-2bc50bf9be1a/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '30 to 35 m2 / 325 to 375 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Desk',
      'Hairdryer',
      'In Main Building',
      'Iron & Board',
      'Landmark View',
      'Magnifying mirror',
      'Minibar',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Shoe kit',
      'Smart TV',
      'Table and chairs set',
      'Tea Set',
    ],
  },
  {
    id: 'deluxe-swim-up',
    title: 'Dive in from your private terrace',
    roomType: 'DELUXE SWIM-UP',
    description:
      'What about adding to your Double room a furnished outdoors terrace with a direct access to the meandering pool and private sun lounger waiting for you to enjoy the splash.',
    price: '31',
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt634/cdf69769-f553-4c82-aa06-e3e8867954fb/image.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt634/cdf69769-f553-4c82-aa06-e3e8867954fb/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt634/c46d320b-89d6-4975-9af0-febbeaf4b450/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '30 to 35 m2 / 325 to 375 sqft',
      'AC',
      'Afternoon Sun',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Desk',
      'Hairdryer',
      'Iron & Board',
      'Magnifying mirror',
      'Minibar',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Piazza View',
      'Pillow Menu',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Shared Pool',
      'Shoe kit',
      'Smart TV',
      'Table and chairs set',
      'Tea Set',
      'Terrace',
    ],
  },
  {
    id: 'rocksuite',
    roomType: 'ROCK SUITE',
    title: 'Supreme luxury with divine views',
    description:
      "Our contemporary Hard Rock Ibiza Suites perfectly capture the authenticity and irreverence of rock 'n' roll with the sensuality and sophistication of Ibiza Island. Three connecting spaces - Living/ lounge, bedroom and bathroom - allowing you to decide when it's time for plugging in or chilling out. Totally unpredictable, totally Ibiza Hard Rock.",
    price: '89',
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/3e7e2260-63e3-4934-9358-ebf08bb6d96a/image.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/3e7e2260-63e3-4934-9358-ebf08bb6d96a/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/cb767423-cda2-4345-9008-dd1a42573ead/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt640/04386083-34f1-4175-8379-685ae5071a12/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '60 to 70 m2 / 645 to 755 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Coffee Machine',
      'Desk',
      'Hairdryer',
      'Hydromassage Bathtub',
      'Iron & Board',
      'Landmark View',
      'Lateral Streets View',
      'Living Room',
      'Magnifying mirror',
      'Minibar',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Pool View',
      'Premium Wi-Fi',
      'Rain shower',
      'Recyclables Coffee Capsules',
      'Safe',
      'Shoe kit',
      'Smart TV',
      'Sofa Bed - Double',
      'Table and chairs set',
      'Tea Set',
    ],
  },
  {
    id: '80s-suite',
    roomType: '80S SUITE',
    title: '80s nostalgia unleashed',
    description:
      "60 square-meter space with an 80s setting, among which vinyl, mirror ball, music cassettes with 80s music and some 80's gifts like a welcome kit that includes a t-shirt.",
    price: '120',
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt635/24fa2b9d-307c-4d23-9021-eb174520dbc0/image.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt641/850e6840-cc2b-48f8-9059-3a64d2b9b097/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt641/f356e89d-6dca-443e-9ac4-9bb975a84b07/image.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt641/e69fa285-5242-4992-831b-7e67d401ba00/image.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '60 to 70 m2 / 645 to 755 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Coffee Machine',
      'Desk',
      'Hairdryer',
      'Hydromassage Bathtub',
      'Iron & Board',
      'King Size Bed',
      'Landmark View',
      'Living Room',
      'Magnifying mirror',
      'Minibar',
      'Morning Sun',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Pool View',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Smart TV',
      'Sofa Bed - Double',
      'Shoe kit',
      'Table and chairs set',
      'Tea Set',
    ],
  },
  {
    id: 'rock-suite-diamond',
    roomType: 'ROCK SUITE DIAMOND',
    title: 'Glam rock with infinite views',
    description:
      'Llega a la cima del rock en este espacio de 75 metros cuadrados auténticamente inspirado en estrellas del rock y que ofrece ese toque de vida glamourosa. Con una exuberancia sin límites, incluye unas vistas infinitas que se prolongan desde la suite hasta la terraza, y una bañera de grifería vista en mitad del dormitorio principal para que no te pierdas el mínimo detalle del paisaje mientras disfrutas de un placer infinito. Estancia de 75 metros cuadrados con capacidad hasta cuatro personas.',
    price: '199',
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt643/5a6459fb-7a86-4d9d-9d9d-acd9a80033d5/original.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt643/5a6459fb-7a86-4d9d-9d9d-acd9a80033d5/original.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt643/e58aeb29-1399-422a-906f-6efc480221c4/original.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt643/40f0715d-3d66-49b7-b71b-cbd8e9d6ed1c/original.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '60 to 70 m2 / 645 to 755 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Coffee Machine',
      'Desk',
      'Hairdryer',
      'Hydromassage Bathtub',
      'Iron & Board',
      'King Size Bed',
      'Landmark View',
      'Living Room',
      'Magnifying mirror',
      'Minibar',
      'Morning Sun',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Pool View',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Smart TV',
      'Sofa Bed - Double',
      'Shoe kit',
      'Table and chairs set',
      'Tea Set',
    ],
  },
  {
    id: 'rock-suite-legend',
    roomType: 'ROCK SUITE LEGEND',
    title: 'Live the rock legend',
    description:
      'Llega a la cima del rock en este espacio de 75 metros cuadrados auténticamente inspirado en estrellas del rock y que ofrece ese toque de vida glamourosa. Con una exuberancia sin límites, incluye unas vistas infinitas que se prolongan desde la suite hasta la terraza, y una bañera de grifería vista en mitad del dormitorio principal para que no te pierdas el mínimo detalle del paisaje mientras disfrutas de un placer infinito. Estancia de 75 metros cuadrados con capacidad hasta cuatro personas.',
    price: '300',
    image:
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt644/b15ce84f-709d-4d46-a0af-2654a645c643/original.webp',
    images: [
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt644/b15ce84f-709d-4d46-a0af-2654a645c643/original.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt644/6f7ea7a0-68df-47ec-8902-0e9a93eb41c1/original.webp',
      'https://hvdatauatstgweu.blob.core.windows.net/roomtypehotelimages/h83/rt644/7dc6a198-3225-49c0-b89e-5fcc4abcf4dc/original.webp',
    ],
    amenities: [
      '24 Hours Room Service',
      '60 to 70 m2 / 645 to 755 sqft',
      'AC',
      'Balcony',
      'Bathrobe and slippers',
      'Bluetooth sound system',
      'Close to Pool',
      'Coffee Machine',
      'Desk',
      'Hairdryer',
      'Hydromassage Bathtub',
      'Iron & Board',
      'King Size Bed',
      'Landmark View',
      'Living Room',
      'Magnifying mirror',
      'Minibar',
      'Morning Sun',
      'Non-smoking Room',
      'Pet Friendly',
      'Phone',
      'Pillow Menu',
      'Pool View',
      'Premium Wi-Fi',
      'Rain shower',
      'Safe',
      'Smart TV',
      'Sofa Bed - Double',
      'Shoe kit',
      'Table and chairs set',
      'Tea Set',
    ],
  },
]
